### ISSUE TITLE
Indizes

### ISSUE THREAD

**Issue by kristina-albrecht** [kristina-albrecht/HANA-SSBM#12]
- Verschiedene Indizes vor allem auf der Faktentabelle
- Indizes nur auf Dimensionstabellen (ob es sich lohn)

**Comment by Meroas** [comment]
Fakten, Dimensionen, gemeinsame Indizes testen

**Comment by Meroas** [comment]
Es sieht so aus, dass die Indizes für die Dimensionen mehr bringen. Könnte jedoch von den Abfragen und entsprechenden Mengen abhängen. Weitere Tests notwendig.
