### ISSUE TITLE
Hints

### ISSUE THREAD

**Issue by kristina-albrecht** [kristina-albrecht/HANA-SSBM#13]
- Vergleich USE_OLAP_PLAN vs. NO_USE_OLAP_PLAN beim Column Store
- OLAP_PARALLEL_AGGREGATION

https://gerardnico.com/db/hana/hint
https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/4ba9edce1f2347a0b9fcda99879c17a1.html

**Comment by Meroas** [comment]
Einfacher Vergleich anhand 1_1 und 3_3 Fertig.

Prio 2: 
Für alle Queries Hints ausprobieren um zu sehen:
a) Welche Engine ist am besten für die Query?
b) Findet der Optimizer diese selbstständig?
